language: ruby
sudo: false
cache:
- apt
- bundler
git:
  submodules: false
rvm:
- 2.2
script:
- true
after_success:
- bundle exec rake clean && bundle exec rake publish
before_install:
- npm update
branches:
  except:
    - /^[0-9]+\.[0-9]+\.[0-9]+$/
