# Dependencies
markdown:         kramdown
redcarpet:
  extensions:    ["with_toc_data"]
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

highlighter:      rouge

# Permalinks
permalink: /:categories/:title

# Setup
title:            "Report Customizer"
#tagline:          'Making Zotero all it can be for us LaTeX holdouts'
description:          'Making Zotero all it can be for us LaTeX holdouts'
baseurl:          https://retorquere.github.io/zotero-report-customizer
#baseurl:          /Users/emile/zotero/report-customizer/site

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

github:
  repo:           https://github.com/retorquere/zotero-report-customizer/
  release:        https://github.com/retorquere/zotero-report-customizer/releases/latest
travis:
  build: https://travis-ci.org/retorquere/zotero-report-customizer
  status: https://travis-ci.org/retorquere/zotero-report-customizer.svg?branch=master

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
